services:
  - type: web
    name: yolov8-security-api
    env: python
    plan: free
    branch: main
    repo: https://github.com/ronymaruga/yolov8-api
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true