services:
  - type: web
    name: yolov8-security-api
    env: docker
    plan: free
    branch: main
    repo: https://github.com/ronymaruga/yolov8-api
    buildCommand: docker build -t yolov8-security-api .
    startCommand: docker run -p 80:80 yolov8-security-api
    autoDeploy: true